# Generated by Django 3.0.7 on 2020-06-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(blank=True, null=True)),
                ('previous', models.IntegerField(blank=True, null=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('currentLogin', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
